[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.12.52"

[[constraint]]
  branch = "master"
  name = "github.com/prometheus/common"

[[constraint]]
  name = "github.com/prometheus/prometheus"
  version = "2.0.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"
