---
version: 2
jobs:
  docker:
    docker:
      - image: alpine:3.21
        environment:
          ECR_REPOSITORY: oneconnect/prometheus-ecs-sd
    steps:
      - run:
          name: Install system dependencies
          command: |
            apk add -U git curl openssh tar gzip aws-cli
      - checkout
      - setup_remote_docker
      - run:
          name: Install Docker client
          command: |
            VER="28.0.4"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run:
          name: Build Docker image
          command: |
            ECR_REPOSITORY_FQDN=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com
            aws ecr get-login-password | docker login --username AWS --password-stdin ${ECR_REPOSITORY_FQDN}
            if [ -n "${CIRCLE_TAG}" ];
              then DOCKER_TAG=${CIRCLE_TAG};
            else DOCKER_TAG=sha-${CIRCLE_SHA1::7};
            fi
            docker build -t ${ECR_REPOSITORY_FQDN}/${ECR_REPOSITORY}:${DOCKER_TAG} .
            docker push ${ECR_REPOSITORY_FQDN}/${ECR_REPOSITORY}:${DOCKER_TAG}
workflows:
  version: 2
  main:
    jobs:
      - docker:
          context: org-global
          filters:
            tags:
              only: /.*/
