---
version: 2
jobs:
  build:
    working_directory: /go/src/github.com/okushchenko/prometheus-ecs-sd
    docker:
      - image: circleci/golang:1.9
    steps:
      - checkout
      - run: make build
      - run: make test
